REPLACE INTO `#__wj_portal_config` (`configname`, `configvalue`, `configfor`) VALUES ('versioncode', '2.1.9', 'default');


ALTER TABLE `#__wj_portal_countries` ADD `localname` VARCHAR(255) NULL DEFAULT NULL AFTER `name`
								, ADD `internationalname` VARCHAR(255) NULL DEFAULT NULL AFTER `localname`
								, ADD `namecode` VARCHAR(255) NULL DEFAULT NULL AFTER `internationalname`;

ALTER TABLE `#__wj_portal_states` ADD `localname` VARCHAR(255) NULL AFTER `name`
								, ADD `internationalname` VARCHAR(255) NULL AFTER `localname`;

ALTER TABLE `#__wj_portal_cities` ADD `localname` VARCHAR(255) NULL AFTER `name`
								, ADD `internationalname` VARCHAR(255) NULL AFTER `localname`;

UPDATE `#__wj_portal_countries` SET `localname` = 'United States', `internationalname` = 'United States', `namecode` = 'us' WHERE `id` = 1;
UPDATE `#__wj_portal_countries` SET `localname` = 'Canada', `internationalname` = 'Canada', `namecode` = 'ca' WHERE `id` = 2;
UPDATE `#__wj_portal_countries` SET `localname` = 'The Bahamas', `internationalname` = 'Bahamas', `namecode` = 'bs' WHERE `id` = 3;
UPDATE `#__wj_portal_countries` SET `localname` = 'Barbados', `internationalname` = 'Barbados', `namecode` = 'bb' WHERE `id` = 4;
UPDATE `#__wj_portal_countries` SET `localname` = 'Belize', `internationalname` = 'Belize', `namecode` = 'bz' WHERE `id` = 5;
UPDATE `#__wj_portal_countries` SET `localname` = 'Bermuda', `internationalname` = 'Bermuda', `namecode` = 'bm' WHERE `id` = 6;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'British Virgin Islands', `namecode` = 'vg' WHERE `id` = 7;
UPDATE `#__wj_portal_countries` SET `localname` = 'Cayman Islands', `internationalname` = 'Cayman Islands', `namecode` = 'ky' WHERE `id` = 8;
UPDATE `#__wj_portal_countries` SET `localname` = 'Costa Rica', `internationalname` = 'Costa Rica', `namecode` = 'cr' WHERE `id` = 9;
UPDATE `#__wj_portal_countries` SET `localname` = 'Cuba', `internationalname` = 'Cuba', `namecode` = 'cu' WHERE `id` = 10;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Dominica', `namecode` = 'dm' WHERE `id` = 11;
UPDATE `#__wj_portal_countries` SET `localname` = 'República Dominicana', `internationalname` = 'Dominican Republic', `namecode` = 'do' WHERE `id` = 12;
UPDATE `#__wj_portal_countries` SET `localname` = 'El Salvador', `internationalname` = 'El Salvador', `namecode` = 'sv' WHERE `id` = 13;
UPDATE `#__wj_portal_countries` SET `localname` = 'Kalaallit Nunaat', `internationalname` = 'Greenland', `namecode` = 'gl' WHERE `id` = 14;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Grenada', `namecode` = 'gd' WHERE `id` = 15;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Guadeloupe', `namecode` = 'gp' WHERE `id` = 16;
UPDATE `#__wj_portal_countries` SET `localname` = 'Guatemala', `internationalname` = 'Guatemala', `namecode` = 'gt' WHERE `id` = 17;
UPDATE `#__wj_portal_countries` SET `localname` = 'Ayiti', `internationalname` = 'Haiti', `namecode` = 'ht' WHERE `id` = 18;
UPDATE `#__wj_portal_countries` SET `localname` = 'Honduras', `internationalname` = 'Honduras', `namecode` = 'hn' WHERE `id` = 19;
UPDATE `#__wj_portal_countries` SET `localname` = 'Jamaica', `internationalname` = 'Jamaica', `namecode` = 'jm' WHERE `id` = 20;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Martinique', `namecode` = 'mq' WHERE `id` = 21;
UPDATE `#__wj_portal_countries` SET `localname` = 'México', `internationalname` = 'Mexico', `namecode` = 'mx' WHERE `id` = 22;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Montserrat', `namecode` = 'ms' WHERE `id` = 23;
UPDATE `#__wj_portal_countries` SET `localname` = 'Nicaragua', `internationalname` = 'Nicaragua', `namecode` = 'ni' WHERE `id` = 24;
UPDATE `#__wj_portal_countries` SET `localname` = 'Panamá', `internationalname` = 'Panama', `namecode` = 'pa' WHERE `id` = 25;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Puerto Rico', `namecode` = 'pr' WHERE `id` = 26;
UPDATE `#__wj_portal_countries` SET `localname` = 'Trinidad and Tobago', `internationalname` = 'Trinidad and Tobago', `namecode` = 'tt' WHERE `id` = 27;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'United States Virgin Islands', `namecode` = 'vi' WHERE `id` = 28;
UPDATE `#__wj_portal_countries` SET `localname` = 'Argentina', `internationalname` = 'Argentina', `namecode` = 'ar' WHERE `id` = 29;
UPDATE `#__wj_portal_countries` SET `localname` = 'Bolivia', `internationalname` = 'Bolivia', `namecode` = 'bo' WHERE `id` = 30;
UPDATE `#__wj_portal_countries` SET `localname` = 'Brasil', `internationalname` = 'Brazil', `namecode` = 'br' WHERE `id` = 31;
UPDATE `#__wj_portal_countries` SET `localname` = 'Chile', `internationalname` = 'Chile', `namecode` = 'cl' WHERE `id` = 32;
UPDATE `#__wj_portal_countries` SET `localname` = 'Colombia', `internationalname` = 'Colombia', `namecode` = 'co' WHERE `id` = 33;
UPDATE `#__wj_portal_countries` SET `localname` = 'Ecuador', `internationalname` = 'Ecuador', `namecode` = 'ec' WHERE `id` = 34;
UPDATE `#__wj_portal_countries` SET `localname` = 'Falkland Islands', `internationalname` = 'Falkland Islands', `namecode` = 'fk' WHERE `id` = 35;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'French Guiana', `namecode` = 'gf' WHERE `id` = 36;
UPDATE `#__wj_portal_countries` SET `localname` = 'Guyana', `internationalname` = 'Guyana', `namecode` = 'gy' WHERE `id` = 37;
UPDATE `#__wj_portal_countries` SET `localname` = 'Paraguay / Paraguái', `internationalname` = 'Paraguay', `namecode` = 'py' WHERE `id` = 38;
UPDATE `#__wj_portal_countries` SET `localname` = 'Perú', `internationalname` = 'Peru', `namecode` = 'pe' WHERE `id` = 39;
UPDATE `#__wj_portal_countries` SET `localname` = 'Suriname', `internationalname` = 'Suriname', `namecode` = 'sr' WHERE `id` = 40;
UPDATE `#__wj_portal_countries` SET `localname` = 'Uruguay', `internationalname` = 'Uruguay', `namecode` = 'uy' WHERE `id` = 41;
UPDATE `#__wj_portal_countries` SET `localname` = 'Venezuela', `internationalname` = 'Venezuela', `namecode` = 've' WHERE `id` = 42;
UPDATE `#__wj_portal_countries` SET `localname` = 'Shqipëria', `internationalname` = 'Albania', `namecode` = 'al' WHERE `id` = 43;
UPDATE `#__wj_portal_countries` SET `localname` = 'Andorra', `internationalname` = 'Andorra', `namecode` = 'ad' WHERE `id` = 44;
UPDATE `#__wj_portal_countries` SET `localname` = 'Հայաստան', `internationalname` = 'Armenia', `namecode` = 'am' WHERE `id` = 45;
UPDATE `#__wj_portal_countries` SET `localname` = 'Österreich', `internationalname` = 'Austria', `namecode` = 'at' WHERE `id` = 46;
UPDATE `#__wj_portal_countries` SET `localname` = 'Azərbaycan', `internationalname` = 'Azerbaijan', `namecode` = 'az' WHERE `id` = 47;
UPDATE `#__wj_portal_countries` SET `localname` = 'Беларусь', `internationalname` = 'Belarus', `namecode` = 'by' WHERE `id` = 48;
UPDATE `#__wj_portal_countries` SET `localname` = 'België / Belgique / Belgien', `internationalname` = 'Belgium', `namecode` = 'be' WHERE `id` = 49;
UPDATE `#__wj_portal_countries` SET `localname` = 'Bosna i Hercegovina / Босна и Херцеговина', `internationalname` = 'Bosnia-Herzegovina', `namecode` = 'ba' WHERE `id` = 50;
UPDATE `#__wj_portal_countries` SET `localname` = 'България', `internationalname` = 'Bulgaria', `namecode` = 'bg' WHERE `id` = 51;
UPDATE `#__wj_portal_countries` SET `localname` = 'Hrvatska', `internationalname` = 'Croatia', `namecode` = 'hr' WHERE `id` = 52;
UPDATE `#__wj_portal_countries` SET `localname` = 'Κύπρος - Kıbrıs', `internationalname` = 'Cyprus', `namecode` = 'cy' WHERE `id` = 53;
UPDATE `#__wj_portal_countries` SET `localname` = 'Česko', `internationalname` = 'Czech Republic', `namecode` = 'cz' WHERE `id` = 54;
UPDATE `#__wj_portal_countries` SET `localname` = 'Danmark', `internationalname` = 'Denmark', `namecode` = 'dk' WHERE `id` = 55;
UPDATE `#__wj_portal_countries` SET `localname` = 'Eesti', `internationalname` = 'Estonia', `namecode` = 'ee' WHERE `id` = 56;
UPDATE `#__wj_portal_countries` SET `localname` = 'Suomi', `internationalname` = 'Finland', `namecode` = 'fi' WHERE `id` = 57;
UPDATE `#__wj_portal_countries` SET `localname` = 'France', `internationalname` = 'France', `namecode` = 'fr' WHERE `id` = 58;
UPDATE `#__wj_portal_countries` SET `localname` = 'საქართველო', `internationalname` = 'Georgia', `namecode` = 'ge' WHERE `id` = 59;
UPDATE `#__wj_portal_countries` SET `localname` = 'Deutschland', `internationalname` = 'Germany', `namecode` = 'de' WHERE `id` = 60;
UPDATE `#__wj_portal_countries` SET `localname` = 'Gibraltar', `internationalname` = 'Gibraltar', `namecode` = 'gi' WHERE `id` = 61;
UPDATE `#__wj_portal_countries` SET `localname` = 'Ελλάς', `internationalname` = 'Greece', `namecode` = 'gr' WHERE `id` = 62;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Guernsey', `namecode` = 'gg' WHERE `id` = 63;
UPDATE `#__wj_portal_countries` SET `localname` = 'Magyarország', `internationalname` = 'Hungary', `namecode` = 'hu' WHERE `id` = 64;
UPDATE `#__wj_portal_countries` SET `localname` = 'Ísland', `internationalname` = 'Iceland', `namecode` = 'is' WHERE `id` = 65;
UPDATE `#__wj_portal_countries` SET `localname` = 'Ireland', `internationalname` = 'Ireland', `namecode` = 'ie' WHERE `id` = 66;
UPDATE `#__wj_portal_countries` SET `localname` = 'Isle of Man', `internationalname` = 'Isle of Man', `namecode` = 'im' WHERE `id` = 67;
UPDATE `#__wj_portal_countries` SET `localname` = 'Italia', `internationalname` = 'Italy', `namecode` = 'it' WHERE `id` = 68;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Jersey', `namecode` = 'je' WHERE `id` = 69;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Kosovo', `namecode` = '' WHERE `id` = 70;
UPDATE `#__wj_portal_countries` SET `localname` = 'Latvija', `internationalname` = 'Latvia', `namecode` = 'lv' WHERE `id` = 71;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Liechtenstein', `namecode` = 'li' WHERE `id` = 72;
UPDATE `#__wj_portal_countries` SET `localname` = 'Lietuva', `internationalname` = 'Lithuania', `namecode` = 'lt' WHERE `id` = 73;
UPDATE `#__wj_portal_countries` SET `localname` = 'Lëtzebuerg', `internationalname` = 'Luxembourg', `namecode` = 'lu' WHERE `id` = 74;
UPDATE `#__wj_portal_countries` SET `localname` = 'Северна Македонија', `internationalname` = 'Macedonia', `namecode` = 'mk' WHERE `id` = 75;
UPDATE `#__wj_portal_countries` SET `localname` = 'Malta', `internationalname` = 'Malta', `namecode` = 'mt' WHERE `id` = 76;
UPDATE `#__wj_portal_countries` SET `localname` = 'Moldova', `internationalname` = 'Moldova', `namecode` = 'md' WHERE `id` = 77;
UPDATE `#__wj_portal_countries` SET `localname` = 'Monaco', `internationalname` = 'Monaco', `namecode` = 'mc' WHERE `id` = 78;
UPDATE `#__wj_portal_countries` SET `localname` = 'Crna Gora / Црна Гора', `internationalname` = 'Montenegro', `namecode` = 'me' WHERE `id` = 79;
UPDATE `#__wj_portal_countries` SET `localname` = 'Nederland', `internationalname` = 'Netherlands', `namecode` = 'nl' WHERE `id` = 80;
UPDATE `#__wj_portal_countries` SET `localname` = 'Norge', `internationalname` = 'Norway', `namecode` = 'no' WHERE `id` = 81;
UPDATE `#__wj_portal_countries` SET `localname` = 'Polska', `internationalname` = 'Poland', `namecode` = 'pl' WHERE `id` = 82;
UPDATE `#__wj_portal_countries` SET `localname` = 'Portugal', `internationalname` = 'Portugal', `namecode` = 'pt' WHERE `id` = 83;
UPDATE `#__wj_portal_countries` SET `localname` = 'România', `internationalname` = 'Romania', `namecode` = 'ro' WHERE `id` = 84;
UPDATE `#__wj_portal_countries` SET `localname` = 'Россия', `internationalname` = 'Russia', `namecode` = 'ru' WHERE `id` = 85;
UPDATE `#__wj_portal_countries` SET `localname` = 'San Marino', `internationalname` = 'San Marino', `namecode` = 'sm' WHERE `id` = 86;
UPDATE `#__wj_portal_countries` SET `localname` = 'Србија', `internationalname` = 'Serbia', `namecode` = 'rs' WHERE `id` = 87;
UPDATE `#__wj_portal_countries` SET `localname` = 'Slovensko', `internationalname` = 'Slovakia', `namecode` = 'sk' WHERE `id` = 88;
UPDATE `#__wj_portal_countries` SET `localname` = 'Slovenija', `internationalname` = 'Slovenia', `namecode` = 'si' WHERE `id` = 89;
UPDATE `#__wj_portal_countries` SET `localname` = 'España', `internationalname` = 'Spain', `namecode` = 'es' WHERE `id` = 90;
UPDATE `#__wj_portal_countries` SET `localname` = 'Sverige', `internationalname` = 'Sweden', `namecode` = 'se' WHERE `id` = 91;
UPDATE `#__wj_portal_countries` SET `localname` = 'Schweiz', `internationalname` = 'Switzerland', `namecode` = 'ch' WHERE `id` = 92;
UPDATE `#__wj_portal_countries` SET `localname` = 'Türkiye', `internationalname` = 'Turkey', `namecode` = 'tr' WHERE `id` = 93;
UPDATE `#__wj_portal_countries` SET `localname` = 'Україна', `internationalname` = 'Ukraine', `namecode` = 'ua' WHERE `id` = 94;
UPDATE `#__wj_portal_countries` SET `localname` = 'United Kingdom', `internationalname` = 'United Kingdom', `namecode` = 'gb' WHERE `id` = 95;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Vatican City', `namecode` = 'va' WHERE `id` = 96;
UPDATE `#__wj_portal_countries` SET `localname` = 'افغانستان', `internationalname` = 'Afghanistan', `namecode` = 'af' WHERE `id` = 97;
UPDATE `#__wj_portal_countries` SET `localname` = 'البحرين', `internationalname` = 'Bahrain', `namecode` = 'bh' WHERE `id` = 98;
UPDATE `#__wj_portal_countries` SET `localname` = 'বাংলাদেশ', `internationalname` = 'Bangladesh', `namecode` = 'bd' WHERE `id` = 99;
UPDATE `#__wj_portal_countries` SET `localname` = 'འབྲུགཡུལ་', `internationalname` = 'Bhutan', `namecode` = 'bt' WHERE `id` = 100;
UPDATE `#__wj_portal_countries` SET `localname` = 'Brunei', `internationalname` = 'Brunei', `namecode` = 'bn' WHERE `id` = 101;
UPDATE `#__wj_portal_countries` SET `localname` = 'ព្រះរាជាណាចក្រ​កម្ពុជា', `internationalname` = 'Cambodia', `namecode` = 'kh' WHERE `id` = 102;
UPDATE `#__wj_portal_countries` SET `localname` = '中国', `internationalname` = 'China', `namecode` = 'cn' WHERE `id` = 103;
UPDATE `#__wj_portal_countries` SET `localname` = 'Timór Lorosa\'e', `internationalname` = 'East Timor', `namecode` = 'tl' WHERE `id` = 104;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Hong Kong', `namecode` = 'hk' WHERE `id` = 105;
UPDATE `#__wj_portal_countries` SET `localname` = 'India', `internationalname` = 'India', `namecode` = 'in' WHERE `id` = 106;
UPDATE `#__wj_portal_countries` SET `localname` = 'Indonesia', `internationalname` = 'Indonesia', `namecode` = 'id' WHERE `id` = 107;
UPDATE `#__wj_portal_countries` SET `localname` = 'ایران', `internationalname` = 'Iran', `namecode` = 'ir' WHERE `id` = 108;
UPDATE `#__wj_portal_countries` SET `localname` = 'العراق', `internationalname` = 'Iraq', `namecode` = 'iq' WHERE `id` = 109;
UPDATE `#__wj_portal_countries` SET `localname` = 'ישראל', `internationalname` = 'Israel', `namecode` = 'il' WHERE `id` = 110;
UPDATE `#__wj_portal_countries` SET `localname` = '日本', `internationalname` = 'Japan', `namecode` = 'jp' WHERE `id` = 111;
UPDATE `#__wj_portal_countries` SET `localname` = 'الأردن', `internationalname` = 'Jordan', `namecode` = 'jo' WHERE `id` = 112;
UPDATE `#__wj_portal_countries` SET `localname` = 'Қазақстан', `internationalname` = 'Kazakhstan', `namecode` = 'kz' WHERE `id` = 113;
UPDATE `#__wj_portal_countries` SET `localname` = 'الكويت', `internationalname` = 'Kuwait', `namecode` = 'kw' WHERE `id` = 114;
UPDATE `#__wj_portal_countries` SET `localname` = 'Кыргызстан', `internationalname` = 'Kyrgyzstan', `namecode` = 'kg' WHERE `id` = 115;
UPDATE `#__wj_portal_countries` SET `localname` = 'ປະເທດລາວ', `internationalname` = 'Laos', `namecode` = 'la' WHERE `id` = 116;
UPDATE `#__wj_portal_countries` SET `localname` = 'لبنان', `internationalname` = 'Lebanon', `namecode` = 'lb' WHERE `id` = 117;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Macau', `namecode` = 'mo' WHERE `id` = 118;
UPDATE `#__wj_portal_countries` SET `localname` = 'Malaysia', `internationalname` = 'Malaysia', `namecode` = 'my' WHERE `id` = 119;
UPDATE `#__wj_portal_countries` SET `localname` = 'ދިވެހިރާއްޖެ', `internationalname` = 'Maldives', `namecode` = 'mv' WHERE `id` = 120;
UPDATE `#__wj_portal_countries` SET `localname` = 'Монгол улс ᠮᠤᠩᠭᠤᠯ ᠤᠯᠤᠰ', `internationalname` = 'Mongolia', `namecode` = 'mn' WHERE `id` = 121;
UPDATE `#__wj_portal_countries` SET `localname` = 'မြန်မာ', `internationalname` = 'Myanmar (Burma)', `namecode` = 'mm' WHERE `id` = 122;
UPDATE `#__wj_portal_countries` SET `localname` = 'नेपाल', `internationalname` = 'Nepal', `namecode` = 'np' WHERE `id` = 123;
UPDATE `#__wj_portal_countries` SET `localname` = '조선민주주의인민공화국', `internationalname` = 'North Korea', `namecode` = 'kp' WHERE `id` = 124;
UPDATE `#__wj_portal_countries` SET `localname` = 'عمان', `internationalname` = 'Oman', `namecode` = 'om' WHERE `id` = 125;
UPDATE `#__wj_portal_countries` SET `localname` = 'پاکستان', `internationalname` = 'Pakistan', `namecode` = 'pk' WHERE `id` = 126;
UPDATE `#__wj_portal_countries` SET `localname` = 'Philippines', `internationalname` = 'Philippines', `namecode` = 'ph' WHERE `id` = 127;
UPDATE `#__wj_portal_countries` SET `localname` = 'قطر', `internationalname` = 'Qatar', `namecode` = 'qa' WHERE `id` = 128;
UPDATE `#__wj_portal_countries` SET `localname` = 'السعودية', `internationalname` = 'Saudi Arabia', `namecode` = 'sa' WHERE `id` = 129;
UPDATE `#__wj_portal_countries` SET `localname` = 'Singapore', `internationalname` = 'Singapore', `namecode` = 'sg' WHERE `id` = 130;
UPDATE `#__wj_portal_countries` SET `localname` = '대한민국', `internationalname` = 'South Korea', `namecode` = 'kr' WHERE `id` = 131;
UPDATE `#__wj_portal_countries` SET `localname` = 'ශ්‍රී ලංකාව இலங்கை', `internationalname` = 'Sri Lanka', `namecode` = 'lk' WHERE `id` = 132;
UPDATE `#__wj_portal_countries` SET `localname` = 'سوريا', `internationalname` = 'Syria', `namecode` = 'sy' WHERE `id` = 133;
UPDATE `#__wj_portal_countries` SET `localname` = '臺灣', `internationalname` = 'Taiwan', `namecode` = 'tw' WHERE `id` = 134;
UPDATE `#__wj_portal_countries` SET `localname` = 'Тоҷикистон', `internationalname` = 'Tajikistan', `namecode` = 'tj' WHERE `id` = 135;
UPDATE `#__wj_portal_countries` SET `localname` = 'ประเทศไทย', `internationalname` = 'Thailand', `namecode` = 'th' WHERE `id` = 136;
UPDATE `#__wj_portal_countries` SET `localname` = 'Türkmenistan', `internationalname` = 'Turkmenistan', `namecode` = 'tm' WHERE `id` = 137;
UPDATE `#__wj_portal_countries` SET `localname` = 'الإمارات العربية المتحدة', `internationalname` = 'United Arab Emirates', `namecode` = 'ae' WHERE `id` = 138;
UPDATE `#__wj_portal_countries` SET `localname` = 'Oʻzbekiston', `internationalname` = 'Uzbekistan', `namecode` = 'uz' WHERE `id` = 139;
UPDATE `#__wj_portal_countries` SET `localname` = 'Việt Nam', `internationalname` = 'Vietnam', `namecode` = 'vn' WHERE `id` = 140;
UPDATE `#__wj_portal_countries` SET `localname` = 'اليمن', `internationalname` = 'Yemen', `namecode` = 'ye' WHERE `id` = 141;
UPDATE `#__wj_portal_countries` SET `localname` = 'الجزائر', `internationalname` = 'Algeria', `namecode` = 'dz' WHERE `id` = 142;
UPDATE `#__wj_portal_countries` SET `localname` = 'Angola', `internationalname` = 'Angola', `namecode` = 'ao' WHERE `id` = 143;
UPDATE `#__wj_portal_countries` SET `localname` = 'Bénin', `internationalname` = 'Benin', `namecode` = 'bj' WHERE `id` = 144;
UPDATE `#__wj_portal_countries` SET `localname` = 'Botswana', `internationalname` = 'Botswana', `namecode` = 'bw' WHERE `id` = 145;
UPDATE `#__wj_portal_countries` SET `localname` = 'Burkina Faso', `internationalname` = 'Burkina Faso', `namecode` = 'bf' WHERE `id` = 146;
UPDATE `#__wj_portal_countries` SET `localname` = 'Burundi', `internationalname` = 'Burundi', `namecode` = 'bi' WHERE `id` = 147;
UPDATE `#__wj_portal_countries` SET `localname` = 'Cameroun', `internationalname` = 'Cameroon', `namecode` = 'cm' WHERE `id` = 148;
UPDATE `#__wj_portal_countries` SET `localname` = 'Cabo Verde', `internationalname` = 'Cape Verde', `namecode` = 'cv' WHERE `id` = 149;
UPDATE `#__wj_portal_countries` SET `localname` = 'Ködörösêse tî Bêafrîka', `internationalname` = 'Central African Republic', `namecode` = 'cf' WHERE `id` = 150;
UPDATE `#__wj_portal_countries` SET `localname` = 'تشاد', `internationalname` = 'Chad', `namecode` = 'td' WHERE `id` = 151;
UPDATE `#__wj_portal_countries` SET `localname` = 'Congo', `internationalname` = 'Congo', `namecode` = 'cg' WHERE `id` = 152;
UPDATE `#__wj_portal_countries` SET `localname` = 'République démocratique du Congo', `internationalname` = 'Democratic Republic of Congo', `namecode` = 'cd' WHERE `id` = 153;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Djibouti', `namecode` = 'dj' WHERE `id` = 154;
UPDATE `#__wj_portal_countries` SET `localname` = 'مصر', `internationalname` = 'Egypt', `namecode` = 'eg' WHERE `id` = 155;
UPDATE `#__wj_portal_countries` SET `localname` = 'Guinea Ecuatorial', `internationalname` = 'Equatorial Guinea', `namecode` = 'gq' WHERE `id` = 156;
UPDATE `#__wj_portal_countries` SET `localname` = 'ኤርትራ Eritrea إرتريا', `internationalname` = 'Eritrea', `namecode` = 'er' WHERE `id` = 157;
UPDATE `#__wj_portal_countries` SET `localname` = 'ኢትዮጵያ', `internationalname` = 'Ethiopia', `namecode` = 'et' WHERE `id` = 158;
UPDATE `#__wj_portal_countries` SET `localname` = 'Gabon', `internationalname` = 'Gabon', `namecode` = 'ga' WHERE `id` = 159;
UPDATE `#__wj_portal_countries` SET `localname` = 'Gambia', `internationalname` = 'Gambia', `namecode` = 'gm' WHERE `id` = 160;
UPDATE `#__wj_portal_countries` SET `localname` = 'Ghana', `internationalname` = 'Ghana', `namecode` = 'gh' WHERE `id` = 161;
UPDATE `#__wj_portal_countries` SET `localname` = 'Guinée', `internationalname` = 'Guinea', `namecode` = 'gn' WHERE `id` = 162;
UPDATE `#__wj_portal_countries` SET `localname` = 'Guiné-Bissau', `internationalname` = 'Guinea-Bissau', `namecode` = 'gw' WHERE `id` = 163;
UPDATE `#__wj_portal_countries` SET `localname` = 'Côte d’Ivoire', `internationalname` = 'Cote DIvory', `namecode` = 'ci' WHERE `id` = 164;
UPDATE `#__wj_portal_countries` SET `localname` = 'Kenya', `internationalname` = 'Kenya', `namecode` = 'ke' WHERE `id` = 165;
UPDATE `#__wj_portal_countries` SET `localname` = 'Lesotho', `internationalname` = 'Lesotho', `namecode` = 'ls' WHERE `id` = 166;
UPDATE `#__wj_portal_countries` SET `localname` = 'Liberia', `internationalname` = 'Liberia', `namecode` = 'lr' WHERE `id` = 167;
UPDATE `#__wj_portal_countries` SET `localname` = 'ليبيا', `internationalname` = 'Libya', `namecode` = 'ly' WHERE `id` = 168;
UPDATE `#__wj_portal_countries` SET `localname` = 'Madagasikara', `internationalname` = 'Madagascar', `namecode` = 'mg' WHERE `id` = 169;
UPDATE `#__wj_portal_countries` SET `localname` = 'Malawi', `internationalname` = 'Malawi', `namecode` = 'mw' WHERE `id` = 170;
UPDATE `#__wj_portal_countries` SET `localname` = 'Mali', `internationalname` = 'Mali', `namecode` = 'ml' WHERE `id` = 171;
UPDATE `#__wj_portal_countries` SET `localname` = 'موريتانيا', `internationalname` = 'Mauritania', `namecode` = 'mr' WHERE `id` = 172;
UPDATE `#__wj_portal_countries` SET `localname` = 'Maurice', `internationalname` = 'Mauritius', `namecode` = 'mu' WHERE `id` = 173;
UPDATE `#__wj_portal_countries` SET `localname` = 'المغرب', `internationalname` = 'Morocco', `namecode` = 'ma' WHERE `id` = 174;
UPDATE `#__wj_portal_countries` SET `localname` = 'Moçambique', `internationalname` = 'Mozambique', `namecode` = 'mz' WHERE `id` = 175;
UPDATE `#__wj_portal_countries` SET `localname` = 'Namibia', `internationalname` = 'Namibia', `namecode` = 'na' WHERE `id` = 176;
UPDATE `#__wj_portal_countries` SET `localname` = 'Niger', `internationalname` = 'Niger', `namecode` = 'ne' WHERE `id` = 177;
UPDATE `#__wj_portal_countries` SET `localname` = 'Nigeria', `internationalname` = 'Nigeria', `namecode` = 'ng' WHERE `id` = 178;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Reunion', `namecode` = 're' WHERE `id` = 179;
UPDATE `#__wj_portal_countries` SET `localname` = 'Rwanda', `internationalname` = 'Rwanda', `namecode` = 'rw' WHERE `id` = 180;
UPDATE `#__wj_portal_countries` SET `localname` = 'São Tomé e Príncipe', `internationalname` = 'Sao Tome and Principe', `namecode` = 'st' WHERE `id` = 181;
UPDATE `#__wj_portal_countries` SET `localname` = 'Sénégal', `internationalname` = 'Senegal', `namecode` = 'sn' WHERE `id` = 182;
UPDATE `#__wj_portal_countries` SET `localname` = 'Sesel', `internationalname` = 'Seychelles', `namecode` = 'sc' WHERE `id` = 183;
UPDATE `#__wj_portal_countries` SET `localname` = 'Sierra Leone', `internationalname` = 'Sierra Leone', `namecode` = 'sl' WHERE `id` = 184;
UPDATE `#__wj_portal_countries` SET `localname` = 'الصومال', `internationalname` = 'Somalia', `namecode` = 'so' WHERE `id` = 185;
UPDATE `#__wj_portal_countries` SET `localname` = 'South Africa', `internationalname` = 'South Africa', `namecode` = 'za' WHERE `id` = 186;
UPDATE `#__wj_portal_countries` SET `localname` = 'السودان', `internationalname` = 'Sudan', `namecode` = 'sd' WHERE `id` = 187;
UPDATE `#__wj_portal_countries` SET `localname` = 'eSwatini', `internationalname` = 'Swaziland', `namecode` = 'sz' WHERE `id` = 188;
UPDATE `#__wj_portal_countries` SET `localname` = 'Tanzania', `internationalname` = 'Tanzania', `namecode` = 'tz' WHERE `id` = 189;
UPDATE `#__wj_portal_countries` SET `localname` = 'Togo', `internationalname` = 'Togo', `namecode` = 'tg' WHERE `id` = 190;
UPDATE `#__wj_portal_countries` SET `localname` = 'تونس', `internationalname` = 'Tunisia', `namecode` = 'tn' WHERE `id` = 191;
UPDATE `#__wj_portal_countries` SET `localname` = 'Uganda', `internationalname` = 'Uganda', `namecode` = 'ug' WHERE `id` = 192;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Western Sahara', `namecode` = 'eh' WHERE `id` = 193;
UPDATE `#__wj_portal_countries` SET `localname` = 'Zambia', `internationalname` = 'Zambia', `namecode` = 'zm' WHERE `id` = 194;
UPDATE `#__wj_portal_countries` SET `localname` = 'Zimbabwe', `internationalname` = 'Zimbabwe', `namecode` = 'zw' WHERE `id` = 195;
UPDATE `#__wj_portal_countries` SET `localname` = 'Australia', `internationalname` = 'Australia', `namecode` = 'au' WHERE `id` = 196;
UPDATE `#__wj_portal_countries` SET `localname` = 'New Zealand', `internationalname` = 'New Zealand', `namecode` = 'nz' WHERE `id` = 197;
UPDATE `#__wj_portal_countries` SET `localname` = 'Viti', `internationalname` = 'Fiji', `namecode` = 'fj' WHERE `id` = 198;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'French Polynesia', `namecode` = 'pf' WHERE `id` = 199;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Guam', `namecode` = 'gu' WHERE `id` = 200;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Kiribati', `namecode` = 'ki' WHERE `id` = 201;
UPDATE `#__wj_portal_countries` SET `localname` = 'Ṃajeḷ', `internationalname` = 'Marshall Islands', `namecode` = 'mh' WHERE `id` = 202;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Micronesia', `namecode` = 'fm' WHERE `id` = 203;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Nauru', `namecode` = 'nr' WHERE `id` = 204;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'New Caledonia', `namecode` = 'nc' WHERE `id` = 205;
UPDATE `#__wj_portal_countries` SET `localname` = 'Papua Niugini', `internationalname` = 'Papua New Guinea', `namecode` = 'pg' WHERE `id` = 206;
UPDATE `#__wj_portal_countries` SET `localname` = 'Sāmoa', `internationalname` = 'Samoa', `namecode` = 'ws' WHERE `id` = 207;
UPDATE `#__wj_portal_countries` SET `localname` = 'Solomon Islands', `internationalname` = 'Solomon Islands', `namecode` = 'sb' WHERE `id` = 208;
UPDATE `#__wj_portal_countries` SET `localname` = 'Tonga', `internationalname` = 'Tonga', `namecode` = 'to' WHERE `id` = 209;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Tuvalu', `namecode` = 'tv' WHERE `id` = 210;
UPDATE `#__wj_portal_countries` SET `localname` = 'Vanuatu', `internationalname` = 'Vanuatu', `namecode` = 'vu' WHERE `id` = 211;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Wallis and Futuna', `namecode` = 'wf' WHERE `id` = 212;
UPDATE `#__wj_portal_countries` SET `localname` = 'Comores Komori جزر القمر', `internationalname` = 'Comoros', `namecode` = 'km' WHERE `id` = 213;
UPDATE `#__wj_portal_countries` SET `localname` = '', `internationalname` = 'Cote DIvorie', `namecode` = 'Cote-DIvorie' WHERE `id` = 214;

INSERT INTO `#__wj_portal_config` (`configname`, `configvalue`, `configfor`, `addon`) VALUES ('show_wpjobportal_page_title', '1', 'wpjobportal', NULL);

UPDATE `#__wj_portal_config` SET `configvalue` = '0' WHERE `configname` = 'newtyped_cities';


